name: CI

on:
  push:

  schedule:
    - cron: "0 0 * * MON"

permissions:
  contents: read

# Cancel existing executions when new commits are pushed onto the branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix flake check

  publish:
    runs-on: ubuntu-22.04
    needs: check
    if: github.ref == 'refs/heads/docker_push'  # FIXME
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # NOTE: Defines ${DOCKER_METADATA_OUTPUT_TAGS}
      - uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - run: |
          nix build .#dockerImage
          ./result | docker load
          docker tag zap-it:latest ${DOCKER_METADATA_OUTPUT_TAGS}
          docker push ${DOCKER_METADATA_OUTPUT_TAGS}
